# Generated by Django 3.2 on 2021-05-17 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_user_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='dateBirth',
            new_name='date_birth',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='updatedAt',
            new_name='updated_at',
        ),
    ]
