# Generated by Django 3.2 on 2021-05-02 01:55

import core.interfaces.abstract_model
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_birth', models.DateField()),
                ('document', models.CharField(max_length=14, unique=True)),
                ('genre', models.IntegerField(choices=[('MALE', 'M'), ('FEMALE', 'F')])),
                ('status', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'person',
            },
            bases=(models.Model, core.interfaces.abstract_model.AbstractModel),
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
