# Generated by Django 3.2 on 2021-05-02 01:58

import core.interfaces.abstract_model
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person.person')),
            ],
            options={
                'db_table': 'person_phone',
            },
            bases=(models.Model, core.interfaces.abstract_model.AbstractModel),
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PersonEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('type', models.IntegerField(choices=[('MAIN', 1), ('WORK', 2), ('COMMERCIAL', 3), ('ADDITIONAL', 4)])),
                ('status', models.IntegerField(choices=[('ENABLED', 1), ('DISABLED', 0)])),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personEmails', to='person.person')),
            ],
            options={
                'db_table': 'person_email',
            },
            bases=(models.Model, core.interfaces.abstract_model.AbstractModel),
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
