# Generated by Django 3.2 on 2021-05-02 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_personemail_personphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='genre',
            field=models.CharField(choices=[('MALE', 'M'), ('FEMALE', 'F')], max_length=6),
        ),
    ]
