# Generated by Django 3.2 on 2021-05-02 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_alter_person_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personemail',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_emails', to='person.person'),
        ),
        migrations.AlterField(
            model_name='personphone',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_phones', to='person.person'),
        ),
    ]
