# Generated by Django 3.2 on 2021-05-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_alter_person_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.SmallIntegerField(choices=[('ENABLED', 1), ('DISABLED', 0)]),
        ),
    ]
