# Generated by Django 3.2 on 2021-05-13 01:57

import core.enums.enum_generic_status
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Windows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=20)),
                ('path', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=8)),
                ('status', models.SmallIntegerField(choices=[(1, 'ENABLED'), (0, 'DISABLED')], default=core.enums.enum_generic_status.EnumGenericStatus['ENABLED'])),
                ('upper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='windows.windows')),
            ],
            options={
                'db_table': 'windows',
            },
        ),
    ]
